on:
  push:
    branches:
      - main

name: Deploy to Amazon ECS-Fargate
                                               
permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:     
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: cn-northwest-1
        role-to-assume: arn:aws-cn:iam::018986110898:role/oidc-Role-26PJF6G3R69O
     #   role-session-name: MySessionName
   
