# This is a basic workflow to help you get started with Actions

name: test-aws-oidc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]



# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws-cn:iam::018986110898:role/my-github-actions-role-test
       # role-to-assume: arn:aws-cn:iam::018986110898:role/github-read
        aws-region: cn-northwest-1

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://oidc
